has_input_skip_aud_checks: true
max_lengths:
  b64u_jwt_no_sig_sha2_padded: 1536
  b64u_jwt_header_w_dot: 300
  b64u_jwt_payload_sha2_padded: 1472
  b64u_jwt_payload: 1472
  sha2_num_bits: 8
  sha2_padding: 64  # TODO: Why do we need a constant for this? It is standardized that SHA2-padding is at most 64 bytes (512 bits)...
  epk: 3
  iss_field: 140
  iss_field_string_bodies: 140
  iss_name: 40
  iss_value: 120
  extra_field: 350
  ev_field: 30
  ev_name: 20
  ev_value: 10
  nonce_field: 105
  nonce_field_string_bodies: 105
  nonce_name: 10
  nonce_value: 100
  aud_field: 140
  aud_field_string_bodies: 140
  aud_name: 40
  private_aud_value: 120
  override_aud_value: 120
  iat_field: 50
  iat_name: 10
  iat_value: 45
  uid_field: 350
  uid_field_string_bodies: 350
  uid_name: 30
  uid_value: 330
