%YAML 1.2
---

resources_dir: "/resources/current_setups"
default_setup_dir: "default"
#new_setup_dir: "new"

zkey_filename: "prover_key.zkey"
witness_gen_binary_filename: "main_c"
test_verification_key_filename: "verification_key.json"
oidc_providers:
  - iss: "test.oidc.provider"
    endpoint_url: "http://mock-on-chain:4444/jwk.json"
jwk_refresh_rate_secs: 10
port: 8080
metrics_port: 9100
enable_dangerous_logging: true
enable_debug_checks: true
enable_federated_jwks: false
enable_jwt_iat_not_in_future_check: true
use_insecure_jwk_for_test: true
