[package]
name = "mock-on-chain"
edition = "2021"

[dependencies]
prover-service = { workspace = true } 
shellexpand = { workspace = true } 
serde = { workspace = true } 
serde_json = { workspace = true } 
aptos-crypto = { workspace = true } 
