---
resources_dir: "~/.local/share/aptos-prover-service"
default_setup_dir: "setup_2024_05"
new_setup_dir: "setup_2024_05"
zkey_filename: "prover_key.zkey"
witness_gen_binary_filename: "main_c"
test_verification_key_filename: "verification_key.json"
oidc_providers:
  - iss: "https://accounts.google.com"
    endpoint_url: "https://www.googleapis.com/oauth2/v3/certs"
  - iss: "test.oidc.provider"
    endpoint_url: "https://github.com/aptos-labs/aptos-core/raw/main/types/src/jwks/rsa/insecure_test_jwk.json"
  - iss: "test.federated.oidc.provider"
    endpoint_url: "https://github.com/aptos-labs/aptos-core/raw/main/types/src/jwks/rsa/secure_test_jwk.json"
jwk_refresh_rate_secs: 10
port: 8083
metrics_port: 9100
enable_dangerous_logging: true
enable_debug_checks: true
enable_test_provider: true
enable_federated_jwks: true
disable_iat_in_past_check: false
