[alias]
xclippy = [
    "clippy",
    "--workspace",
    "--all-targets",
    "--",
    "-Dwarnings",
    "-Wclippy::all",
    "-Aclippy::upper_case_acronyms",
    "-Aclippy::enum-variant-names",
    "-Aclippy::result-large-err",
    "-Aclippy::mutable-key-type",
    "-Wclippy::needless-borrow",
]

[build]
rustflags = ["--cfg", "tokio_unstable"]

[env]
# These are required for renaming axum metrics to be specific to prover
AXUM_HTTP_REQUESTS_TOTAL = "prover_requests_total"
AXUM_HTTP_REQUESTS_DURATION_SECONDS = "prover_request_duration_secs"
AXUM_HTTP_REQUESTS_PENDING = "prover_requests_pending"
AXUM_HTTP_RESPONSE_BODY_SIZE = "prover_response_body_size"
