name: Build image

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: Set up Depot CLI
      #   uses: depot/setup-action@v1

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: false
          token_format: "access_token"
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Login to us-central1 Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./prover-service/Dockerfile
          push: true
          tags: |
            us-docker.pkg.dev/aptos-registry/docker/prover-service:latest
            us-docker.pkg.dev/aptos-registry/docker/prover-service:${{ github.sha }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            RELEASE_DEFAULT=test_releases/test-ceremony-20250224
            RELEASE_NEW=test_releases/test-ceremony-20250224

      - run: echo "" > ~/.bashrc
      - run: ./scripts/task.sh prover-service install-deps
      - run: ./scripts/task.sh setup download-ceremonies-for-releases "test_releases/test-ceremony-20250224" "test_releases/test-ceremony-20250224"
      - run: source ~/.bashrc; ./scripts/task.sh prover-service test-docker-image "test_releases/test-ceremony-20250224"
