name: run-cargo-test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest-16-core
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: ./scripts/setup_environment.sh prover-service:install-deps 
      - run: cargo fmt --check && cargo xclippy
  rust:
    name: Run cargo test
    runs-on: ubuntu-latest-16-core
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: ./scripts/setup_environment.sh prover-service:install-deps circuit:install-deps trusted-setup:download-latest-setup trusted-setup:download-latest-witness-gen-wasm 
      - run: chmod -R 777 ~/.local/share/aptos-prover-service/
      - run: LD_LIBRARY_PATH=$(pwd)/rust-rapidsnark/rapidsnark/build/subprojects/oneTBB-2022.0.0 cargo test
