name: run-cargo-test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest-16-core
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: sudo apt-get update -y && sudo apt-get install -y gcc clang cmake make libyaml-dev nasm libgmp-dev libomp-dev
      - run: cargo fmt --check && cargo xclippy
  rust:
    name: Run cargo test
    runs-on: ubuntu-latest-16-core
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: bash ./dev_setup.sh
      - run: npm root -g
      - run: which npm
      - run: chmod -R 777 ~/.local/share/aptos-prover-service
      - run: sudo apt-get update -y && sudo apt-get install -y gcc clang cmake make libyaml-dev nasm libgmp-dev libomp-dev
      - run: realpath .
      - run: LD_LIBRARY_PATH=$(pwd)/prover/rust-rapidsnark/rapidsnark/package/lib cargo test
